import { createContext } from 'react'

export type Language = 'en' | 'zh'

export const enDict = {
  appTitle: '13F Tracker Pro',
  searchPlaceholder: 'Filter by institution, manager, style, or ticker',
  institutionsAvailable: '12 institutions',
  dataQuarter: 'Data quarter',
  selectYear: 'Year',
  selectQuarter: 'Quarter',
  latestSnapshot: 'Latest',
  dataDisclaimer: 'Data sourced from SEC EDGAR. For informational purposes only.',
  dataLoadFailed: 'Data failed to load.',
  retry: 'Retry',
  noResults: 'No matching records found.',
  loadingHistoricalFilings: 'Loading SEC filing snapshot...',
  snapshotOnly: 'Archived static snapshot. Use the quarter selector to switch between saved datasets.',
  mixedSnapshotNotice: 'This archived snapshot is not uniform across all institutions.',
  snapshotLabel: 'Bundled snapshot',
  latestFilingUnavailable: 'Unavailable in current snapshot',
  heatLabel: 'Heat',
  totalInstitutionsShort: '12 inst',
  heldByInstitutions: 'held by institutions',
  trackedInstitutions: 'Tracked Institutions',
  fundsMapped: 'funds mapped',
  holdings: 'Holdings',
  clickAnyBlock: 'Click any block below to view holding details',
  popularTreemapTitle: 'Popular Holdings Treemap',
  popularTreemapSub: 'Area sized by coverage, average weight, and aggregated value. Click any tile to inspect stock holders.',
  focused: 'Focused',
  avg: 'avg',
  institutions: 'institutions',
  clear: 'Clear',
  backToDashboard: 'Back to Dashboard',
  currentQuarter: 'Current Quarter',
  quarterEndNetAssets: 'Quarter-End Net Assets',
  holdingsCount: 'Holdings Count',
  latestFilingDate: 'Latest Filing Date',
  reportDate: 'Report Date',
  portfolioEvolution: 'Portfolio Evolution (Net Assets)',
  portfolioEvolutionSub: 'Historical reported 13F values available in the bundled snapshot',
  netAssets: 'Net Assets',
  oneYChange: '1Y Change',
  maxDrawdown: 'Max Drawdown',
  volatility: 'Volatility',
  sinceTrough: 'Since Trough',
  low: 'Low',
  med: 'Medium',
  high: 'High',
  institutionStyleVsSp500: 'Institution Style vs S&P 500',
  sectorAllocation: 'Sector Allocation Comparison',
  sectorMethodology: 'Classification uses a local GICS-style mapping; S&P 500 benchmark uses a static ETF holdings proxy.',
  benchmarkAsOf: 'Benchmark as of',
  unclassifiedWeight: 'Unclassified weight',
  dominantStyle: 'Dominant Style',
  top2Concentration: 'Top-2 Concentration',
  combinedStyleWeight: 'Combined style weight',
  styleBreadth: 'Style Breadth',
  segmentsAbove10: 'Segments above 10%',
  segment: 'Segment',
  weight: 'Weight',
  vsSp500: 'vs S&P 500',
  quarterlyHoldingsOverview: 'Quarterly Holdings Overview',
  totalPositions: 'Total Positions',
  security: 'Security',
  mktValueB: 'Mkt Value (B)',
  qoqDelta: 'QoQ Delta',
  showingTopHoldings: 'Showing top holdings',
  topHoldingsOnly: 'Only top positions are bundled in this static dataset.',
  qoqPositionChanges: 'Quarter-over-Quarter Position Changes',
  topAdds: 'Top Adds',
  byBuyIntensity: '(by Buy Intensity)',
  delta: 'Delta ($)',
  shareChg: 'Share Chg',
  postWgt: 'Post Wgt',
  topTrims: 'Top Trims',
  bySellIntensity: '(by Sell Intensity)',
  new: 'New',
  add: 'Add',
  trim: 'Trim',
  exit: 'Exit',
  hold: 'Hold',

  // New features
  totalBought: 'Total Bought',
  totalSold: 'Total Sold',
  netCapitalFlow: 'Net Capital Flow',
  turnoverRate: 'Turnover Rate',
  cashReserves: 'Cash Reserves',
  cashQoQChange: 'Cash QoQ Change',
  shares: 'Shares',
  shareChange: 'Share Change',
  weightQoQ: 'Weight QoQ',
  action: 'Action',
  capitalFlowTitle: 'Quarterly Capital Flow (Sankey)',
  capitalFlowSub: 'Interactive visualization of capital movement from trimmed/exited holdings into added/new positions',
  sectorDriftTitle: 'Sector Allocation Drift',
  sectorDriftSub: 'Historical evolution of portfolio exposure across GICS sectors over time',
  consensusTitle: 'Smart Money Consensus',
  consensusSub: 'Cross-institutional consensus analysis across 12 elite global hedge funds',
  topConsensusBuys: 'Top Consensus Buys',
  topConsensusTrims: 'Top Consensus Trims',
  topConsensusHoldings: 'Top Consensus Holdings',
  highestConvictionBets: 'Highest Conviction Bets',
  allStarTitle: 'Wall Street All-Star Index',
  allStarSub: 'Equal-weighted & conviction-weighted composite index built from elite institutional consensus',
  equalWeighted: 'Equal-Weighted (1/N)',
  convictionWeighted: 'Conviction-Weighted',
  tickerDetailTitle: 'Institutional Ownership 360°',
  holdingInstitutions: 'Holding Institutions',
  allStarNav: 'All-Star Index',
  consensusNav: 'Smart Money Consensus',
  dashboardNav: 'Institutions',
  viewTickerDetail: 'View Stock Holders',
  buyerCount: 'Buyers',
  sellerCount: 'Sellers',
  holderCount: 'Holders',
  officialFilingNote: 'Official SEC Report / Portfolio Liquidity Model',
  buyersList: 'Top Buyers',
  sellersList: 'Top Sellers',
  topHolders: 'Institutional Holders',
  constituents: 'Constituents',
  sectorBreakdown: 'Sector Breakdown',
  trackCapital: 'Tracked Capital',
  convictionWeight: 'Conviction Wgt',
  equalWeight: 'Equal Wgt',
  mainAction: 'Consensus Action',
}

export type TranslationKey = keyof typeof enDict
export type TranslationDict = Record<TranslationKey, string>

export const zhDict: TranslationDict = {
  appTitle: '13F 机构追踪终端',
  searchPlaceholder: '按机构、经理、风格或股票代码筛选',
  institutionsAvailable: '12 家顶级机构',
  dataQuarter: '数据季度',
  selectYear: '年份',
  selectQuarter: '季度',
  latestSnapshot: '最新',
  dataDisclaimer: '数据来自 SEC EDGAR，仅供信息参考。',
  dataLoadFailed: '数据加载失败。',
  retry: '重试',
  noResults: '没有找到匹配的记录。',
  loadingHistoricalFilings: '正在加载 SEC 披露快照...',
  snapshotOnly: '已归档静态快照。可以用季度选择器切换已保存的数据集。',
  mixedSnapshotNotice: '当前归档快照并非所有机构都处在同一披露季度。',
  snapshotLabel: '已打包快照',
  latestFilingUnavailable: '当前快照未提供',
  heatLabel: '热度',
  totalInstitutionsShort: '12 家',
  heldByInstitutions: '家机构持有',
  trackedInstitutions: '跟踪机构',
  fundsMapped: '家基金已映射',
  holdings: '持仓',
  clickAnyBlock: '点击下方任意区块查看持仓详情',
  popularTreemapTitle: '热门持仓热力图',
  popularTreemapSub: '面积按覆盖度、平均权重和聚合市值计算。点击任意图块可穿透查看持有该股的所有机构。',
  focused: '聚焦',
  avg: '平均',
  institutions: '家机构',
  clear: '清除',
  backToDashboard: '返回总览',
  currentQuarter: '当前季度',
  quarterEndNetAssets: '季末美股持仓',
  holdingsCount: '持仓标的数',
  latestFilingDate: '最新申报日期',
  reportDate: '报告期日期',
  portfolioEvolution: '美股资产规模演变',
  portfolioEvolutionSub: '展示当前打包快照内可用的历史 13F 资产规模',
  netAssets: '净资产',
  oneYChange: '近 1 年变化',
  maxDrawdown: '最大回撤',
  volatility: '波动率',
  sinceTrough: '自低点反弹',
  low: '低',
  med: '中',
  high: '高',
  institutionStyleVsSp500: '机构风格 vs S&P 500',
  sectorAllocation: '板块配置对比',
  sectorMethodology: '分类使用本地 GICS 风格映射；S&P 500 基准使用静态 ETF 持仓代理。',
  benchmarkAsOf: '基准日期',
  unclassifiedWeight: '未分类权重',
  dominantStyle: '主导风格',
  top2Concentration: '前二集中度',
  combinedStyleWeight: '合计权重',
  styleBreadth: '风格广度',
  segmentsAbove10: '超过 10% 的板块数',
  segment: '板块',
  weight: '权重',
  vsSp500: '相对 S&P 500',
  quarterlyHoldingsOverview: '当季持仓概览',
  totalPositions: '个持仓',
  security: '标的',
  mktValueB: '市值（十亿美元）',
  qoqDelta: '市值环比变化',
  showingTopHoldings: '当前展示前几大持仓',
  topHoldingsOnly: '当前静态数据集只打包头部持仓。',
  qoqPositionChanges: '季度持仓变化',
  topAdds: '增持榜',
  byBuyIntensity: '（按买入力度）',
  delta: '变化额（美元）',
  shareChg: '股数变化',
  postWgt: '最新权重',
  topTrims: '减持榜',
  bySellIntensity: '（按卖出力度）',
  new: '新建仓',
  add: '增持',
  trim: '减持',
  exit: '清仓',
  hold: '持平',

  // New features
  totalBought: '当季买入总值',
  totalSold: '当季卖出总值',
  netCapitalFlow: '净资金流向',
  turnoverRate: '换手率',
  cashReserves: '期末现金储备',
  cashQoQChange: '现金环比增减',
  shares: '持股数',
  shareChange: '股数变化',
  weightQoQ: '权重环比',
  action: '操作',
  capitalFlowTitle: '季度资金流向（买卖桑基图）',
  capitalFlowSub: '直观呈现从减持/清仓标的流出，并注入到增持/新建仓标的的资金流转路径',
  sectorDriftTitle: '行业配置风格历季漂移',
  sectorDriftSub: '展示历季度在 GICS 11 大行业板块上的配置权重迁移轨迹',
  consensusTitle: '聪明钱共识看板',
  consensusSub: '聚合 12 家全球顶级投资机构的当季调仓共识与资金流向',
  topConsensusBuys: '顶流大佬共同增持榜',
  topConsensusTrims: '顶流大佬共同减持榜',
  topConsensusHoldings: '顶流大佬最爱重仓榜',
  highestConvictionBets: '独门高信念重仓榜',
  allStarTitle: '华尔街全明星精选指数',
  allStarSub: '基于 12 大顶级机构核心共识持仓构建的超级投资家精选组合',
  equalWeighted: '等权重 (Equal-Weighted)',
  convictionWeighted: '信念市值加权 (Conviction-Weighted)',
  tickerDetailTitle: '个股机构持仓 360° 穿透',
  holdingInstitutions: '持有该股的顶级机构',
  allStarNav: '全明星指数',
  consensusNav: '聪明钱共识',
  dashboardNav: '机构看板',
  viewTickerDetail: '查看机构持仓穿透',
  buyerCount: '买入机构数',
  sellerCount: '卖出机构数',
  holderCount: '持有机构数',
  officialFilingNote: '官方 10-Q 季报 / 组合流动性测算',
  buyersList: '主要买入机构',
  sellersList: '主要卖出机构',
  topHolders: '持仓机构明细',
  constituents: '指数成分股',
  sectorBreakdown: '行业分布',
  trackCapital: '跟踪资金规模',
  convictionWeight: '信念权重',
  equalWeight: '等权重',
  mainAction: '共识方向',
}

export interface LanguageContextValue {
  language: Language
  toggleLanguage: () => void
  lang: TranslationDict
}

export const LanguageContext = createContext<LanguageContextValue | null>(null)

export function getInitialLanguage(): Language {
  if (typeof window === 'undefined') {
    return 'en'
  }

  const savedLanguage = window.localStorage.getItem('app-language')
  return savedLanguage === 'zh' ? 'zh' : 'en'
}
